// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hybrid_cache.Context;

#nullable disable

namespace hybrid_cache.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hybrid_cache.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estoque = 50,
                            Nome = "Produto 1",
                            Preco = 99.99m
                        },
                        new
                        {
                            Id = 2,
                            Estoque = 30,
                            Nome = "Produto 2",
                            Preco = 150.00m
                        },
                        new
                        {
                            Id = 3,
                            Estoque = 20,
                            Nome = "Produto 3",
                            Preco = 299.50m
                        },
                        new
                        {
                            Id = 4,
                            Estoque = 12,
                            Nome = "Produto 4",
                            Preco = 299.50m
                        },
                        new
                        {
                            Id = 5,
                            Estoque = 33,
                            Nome = "Produto 5",
                            Preco = 55.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
